---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    includes:
       in_header: ga.html
editor_options:
  chunk_output_type: console
---

Welcome to my collection of teaching materials.

## Epidemiology

* [DTHBTN - Dịch tễ học bệnh truyền nhiễm](https://decidelab.github.io/teaching_materials/DTHBTN_BenhTruyenNhiem.html)
* [DTHBTN - Dịch tễ học bệnh lây qua đường tiêu hoá](https://decidelab.github.io/teaching_materials/DTHBTN_BenhDuongTieuHoa.html)
* [DTHBTN - Dịch tễ học bệnh lây qua vectơ](https://decidelab.github.io/teaching_materials/DTHBTN_BenhLayQuaVecto.html)

## Slide

* [DTHCB - Bệnh và Sự xuất hiện Dịch](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_BenhDich.html)
* [DTHCB - DTH Phân tích](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_DTHPT.html)
* [DTHCB - Số đo bệnh trạng](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_SDBT.html)
* [DTHCB - Số đo kết hợp](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_SDKH.html)
* [DTHCB - Số đo kết hợp - Bài tập](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_BTSDKH.html)
* [DTHCB - Suy diễn nhân quả](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_SDNQ.html)
* [DTHCB - Suy diễn nhân quả (SĐH)](https://decidelab.github.io/teaching_materials/slides/Slide_DTHCB_SDH_SDNQ_20210504.html)
* [DTHBKL - Tổng quan y văn](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBKL_TQYV_YHDP_20210305.html)
* [DTHBKL - DTH Sức khoẻ tâm thần](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBKL_MentalHealth.html)
* [DTHBKL - DTH Sức khoẻ tâm thần (YHDP)](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBKL_MentalHealth_YHDP_20210325.html)
* [DTHBTN - Bệnh lây qua đường tiêu hoá](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBTN_BTH.html)
* [DTHBTN - Bệnh lây qua vectơ](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBTN_BV.html)
* [DTHBTN - Bệnh lây qua đường hô hấp](https://decidelab.github.io/teaching_materials/slides/Slide_DTHBTN_BHH.html)

* [DDLS - Tìm kiếm và quản lý tài liệu tham khảo](https://decidelab.github.io/teaching_materials/slides/Slide_DDLS_TLTK_20210310)

* [DTHLS - Tìm kiếm và phê bình y văn](https://decidelab.github.io/teaching_materials/slides/Slide_DTHLS_YVan_20210416.html)
* [DTHLS - Các số đo trong nghiên cứu lâm sàng](https://decidelab.github.io/teaching_materials/slides/Slide_DTHLS_SoDo_202104092.html)
* [DTHLS - Nghiên cứu tiên lượng](https://decidelab.github.io/teaching_materials/slides/Slide_DTHLS_NCTL2_20210423.html)
* [DTHLS - Mô hình tiên lượng trong sốt dengue](https://decidelab.github.io/teaching_materials/slides/Slide_DTHLS_MHTLDengue_20210423.html)
* [DTHLS - Ra quyết định lâm sàng](https://decidelab.github.io/teaching_materials/slides/Slide_DTHLS_QDLS_20210507.html)



